# Generated by Django 4.0.6 on 2024-06-09 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='CurricularUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=15)),
                ('ects', models.IntegerField()),
                ('cu_readable_code', models.CharField(max_length=50)),
                ('time_spent', models.TimeField()),
                ('cu_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deisicourses.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Programming_Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('curricular_units', models.ManyToManyField(to='deisicourses.curricularunit')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('video_link', models.URLField(blank=True, max_length=250, null=True)),
                ('git_repo_link', models.URLField(blank=True, max_length=250, null=True)),
                ('curricular_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='deisicourses.curricularunit')),
                ('programming_languages', models.ManyToManyField(to='deisicourses.programming_language')),
            ],
        ),
        migrations.AddField(
            model_name='curricularunit',
            name='programming_languages',
            field=models.ManyToManyField(to='deisicourses.programming_language'),
        ),
        migrations.AddField(
            model_name='curricularunit',
            name='teachers',
            field=models.ManyToManyField(to='deisicourses.teacher'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('presentation', models.TextField()),
                ('objectives', models.TextField()),
                ('competences', models.TextField()),
                ('scientific_area', models.CharField(max_length=50)),
                ('deliberation', models.URLField(blank=True, max_length=250, null=True)),
                ('career_opportunities', models.TextField()),
                ('curricular_units', models.ManyToManyField(to='deisicourses.curricularunit')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deisicourses.teacher')),
            ],
        ),
    ]
