# Generated by Django 4.0.6 on 2024-03-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrongOpinions', '0002_category_article_created_at_article_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_authors',
            field=models.ManyToManyField(blank=True, related_name='followers_relationships', to='wrongOpinions.author'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to='wrongOpinions.author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to='wrongOpinions.user')),
            ],
        ),
    ]
